<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Friday, April 12, 2024 2:00:23 PM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">testing</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x0000026E09B54890&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "D:\working\xml_to_layer.py", line 282, in &lt;module&gt;
    main()
  File "D:\working\xml_to_layer.py", line 275, in main
    create_structures_feature_from_OH_conductor(dst_structures, dst_gdb)
  File "D:\working\xml_to_layer.py", line 214, in create_structures_feature_from_OH_conductor
    for row in cursor:
RuntimeError: Cannot find field 'ARC_FROM_STRUCTURE'
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Friday, April 12, 2024 2:01:22 PM (Elapsed Time: 59.70 seconds)</msg></messages>