<?xml version="1.0" encoding="utf-8"?><messages><msg code="0" type="2">Start Time: Saturday, April 13, 2024 9:30:38 PM</msg><msg code="0" type="0">
 1. Creating outputs
</msg><msg code="0" type="0">    - Spans</msg><msg code="0" type="0">&lt;geoprocessing spatial reference object object at 0x0000022C57CD0B70&gt;</msg><msg code="0" type="0">    - Structures</msg><msg code="0" type="0">    - Sections</msg><msg code="0" type="0">getting arc pro list</msg><msg code="0" type="0">ETL.1840</msg><msg code="0" type="0">getting arc pro list</msg><msg code="0" type="0">ETL.1840</msg><msg code="0" type="0">((6406425.521, 1790005.6610000003), (6406682.9629999995, 1790069.6329999994)), ((6410361.203, 1790877.0130000003), (6410939.392000001, 1791333.7660000008))</msg><msg code="-2147467259" type="100">Traceback (most recent call last):
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 400, in &lt;module&gt;
    main()
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 393, in main
    create_sections_feature_from_OH_conductor(dst_sections, dst_gdb, get_arc_pro_list(), sr=xml_sr )
  File "C:\Users\rifra\Xml-to-layer-arc-tool\xml_to_layer.py", line 332, in create_sections_feature_from_OH_conductor
    [arcpy.Point(vertices_to_keep[counter_1][0], vertices_to_keep[counter_1][1]), arcpy.Point(vertices_to_keep[counter_1+1][0], vertices_to_keep[counter_1+1][1])]
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\mixins.py", line 1101, in __init__
    setattr(self, attr, value)
  File "C:\Program Files\ArcGIS\Pro\Resources\ArcPy\arcpy\arcobjects\_base.py", line 109, in _set
    return setattr(self._arc_object, attr_name, cval(val))
RuntimeError: Point: Input value is not numeric
</msg><msg code="0" type="0">Failed script Script...</msg><msg code="-2147467259" type="100">Failed to execute (Script).</msg><msg code="0" type="3">Failed at Saturday, April 13, 2024 9:31:06 PM (Elapsed Time: 27.91 seconds)</msg></messages>